- name: Install elasticsearch
  hosts: elasticsearch
  become: yes
  become_user: root
  tasks:
    - name: download elasticsearch
      get_url:
        url: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/e/elasticsearch/elasticsearch-7.17.9-amd64.deb"
        dest: "/root/elasticsearch-7.17.9-amd64.deb"
    - name: install elastic
      apt:
        deb: "/root/elasticsearch-7.17.9-amd64.deb"
    - name: update
      apt:
        update_cache: yes
    - name: daemon reload
      systemd:
        daemon_reload: true
        name: elasticsearch.service
        state: started
    - name: move conf file
      copy:
        src: config.yml
        dest: /etc/elasticsearch/elasticsearch.yml
        backup: true
    - name: restart elastic
      systemd:
        name: elasticsearch.service
        state: restarted
